/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./context/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "brand-blue": "#1e3a8a",
        "brand-yellow": "#facc15",
        "brand-red": "#dc2626",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Poppins", "sans-serif"],
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        konark: {
          primary: "#1e3a8a",
          "primary-content": "#ffffff",
          secondary: "#7c3aed",
          "secondary-content": "#ffffff",
          accent: "#facc15",
          "accent-content": "#000000",
          neutral: "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f3f4f6",
          "base-300": "#e5e7eb",
          "base-content": "#1f2937",
          info: "#3b82f6",
          "info-content": "#ffffff",
          success: "#22c55e",
          "success-content": "#ffffff",
          warning: "#f59e0b",
          "warning-content": "#000000",
          error: "#ef4444",
          "error-content": "#ffffff",
        },
        konarkDark: {
          primary: "#3b82f6",
          "primary-content": "#ffffff",
          secondary: "#8b5cf6",
          "secondary-content": "#ffffff",
          accent: "#fbbf24",
          "accent-content": "#000000",
          neutral: "#1e293b",
          "neutral-content": "#f1f5f9",
          "base-100": "#0f172a",
          "base-200": "#1e293b",
          "base-300": "#334155",
          "base-content": "#f1f5f9",
          info: "#60a5fa",
          "info-content": "#000000",
          success: "#34d399",
          "success-content": "#000000",
          warning: "#fbbf24",
          "warning-content": "#000000",
          error: "#f87171",
          "error-content": "#000000",
        },
      },
      "light",
      "dark",
      "cupcake",
      "corporate",
      "business",
    ],
    darkTheme: "konarkDark",
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
  darkMode: ["class", '[data-theme="konarkDark"]'],
};
